vim.cmd.packadd({ vim.fn.escape("specialist.nvim", " "), bang = true, magic = { file = false } })

-- TODO: The cw custom comand does not stop at delimiters like quotes
-- "$"
-- if you cw on $, it will also take out the quote boundary
-- In the part where it determines what words are, delimiters need to be considered separately
-- TODO: @param
-- if you cw on the p it takes you before the @
-- and with ] from end of line
-- TODO:
-- some line: ?
-- stuff
-- cw before the ? mark, it will go down to the next line and grab the --
-- TODO:
-- stuff, "other stuff"
-- do ca" in other stuff. goes before the comma. I'm not even sure that one's me
-- TODO: because the maps create on bufreadpre, if I open a harpoon dialog, dd doesn't work
-- I doubt harpoon is the only use case for this type of thing
-- The issue right now is that the plug maps are made before the underlying data is ready, I
-- think. Because If a plug map doesn't find anything, I think it just moves on gracefully
-- TODO: dj on the last line does not delete the current one. Unsure if this is default or not
