-- local api = vim.api
-- local fn = vim.fn

-- for i = 1, #jump_maps do
--     local map = jump_maps[i]
--     local modes = map[1]
--     local key = map[2]
--     local rhs = map[3]
--     for j = 1, #modes do
--         local mode = modes[j]
--         local maparg_res = fn.maparg(key, mode)
--         -- Need to check for just <cr> because of unsimplification (:h <tab>)
--         local res_string = type(maparg_res) == "string"
--         if res_string and (maparg_res == "" or string.lower(maparg_res) == key) then
--             api.nvim_set_keymap(mode, key, rhs, { noremap = true })
--         end
--     end
-- end
-- TODO: Make sure the business with properly mapping <cr> is transferred over when this module
-- is re-written.
